GRAPHS = $(./%.jgr)
JGRAPH = /home/jplank/bin/LINUX-X86_64/jgraph

all:
	$(JGRAPH) name_box.jgr    > name_box.ps
	$(JGRAPH) ability_mod.jgr > ability_mod.ps
	$(JGRAPH) prof_bonus.jgr  > prof_bonus.ps
	$(JGRAPH) heroic_ins.jgr  > heroic_ins.ps
	$(JGRAPH) initiative.jgr  > initiative.ps
	$(JGRAPH) speed.jgr       > speed.ps
	$(JGRAPH) size.jgr        > size.ps
	$(JGRAPH) pass_perc.jgr   > pass_perc.ps
	$(JGRAPH) level.jgr       > level.ps
	$(JGRAPH) ac.jgr          > ac.ps
	$(JGRAPH) health.jgr      > health.ps
	$(JGRAPH) hitdice.jgr     > hitdice.ps
	$(JGRAPH) skills.jgr      > skills.ps
	$(JGRAPH) weaps_tools.jgr > weaps_tools.ps
	$(JGRAPH) feat.jgr        > feat.ps
	$(JGRAPH) equipped.jgr    > equipped.ps